//-----------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="B'15, IIT Palakkad">
//      Open Source. Feel free to use the code, but don't forget to acknowledge. 
// </copyright>
// <author>
//     autogenerated
// </author>
// <review>
//      Libin N George
// </review>
//-----------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", Justification = "Only need an exception raised. Name of exception does not matter", MessageId = "e", Scope = "member", Target = "Masti.Schema.CorruptedDataEncodingDecodingMessageSchemaTest.#Run()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Justification = "Only need an exception raised. Name of exception does not matter", Target = "Masti.Schema.CorruptedDataEncodingDecodingImageSchemaTest.#Run()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Justification = "Only need an exception raised. Name of exception does not matter", Target = "Masti.Schema.CorruptedDataEncodingDecodingMessageSchemaTest.#Run()")]